databases:
  - name: BudgetApp
    databaseName: <%= ENV["DATABASE_URL"] %>
    user: budget_app_development

services:
  - type: web
    name: BudgetApp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV["DATABASE_URL"] %>
        fromDatabase:
          name: <%= ENV["DATABASE_URL"] %>
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false